# Generated by Django 4.2 on 2024-03-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solana_wallet', models.CharField(max_length=100, unique=True)),
                ('telegram_username', models.CharField(max_length=100)),
                ('quote_retweet_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referal_count', models.IntegerField()),
            ],
        ),
    ]
