# Generated by Django 5.0.3 on 2024-03-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referal_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
