# Generated by Django 5.0.3 on 2024-03-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0003_remove_user_referal_count_user_referral_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=650000),
        ),
    ]
