# Generated by Django 5.0.3 on 2024-03-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0002_user_referral_id_alter_user_referal_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referal_count',
        ),
        migrations.AddField(
            model_name='user',
            name='referral_count',
            field=models.IntegerField(default=0),
        ),
    ]
